import uuid, os
if os.name == "nt": os.system("title Index V0.2")

index = input("Welcome to the index!(rev) Search: ")

if index == 'What is google?':
    input("Google is a big company, and its the creator of Google Chrome!")
    print("")
    input("Restart to see another index!")
elif index == 'What is windows?':
     input("Windows is an operating system, made by microsoft!")
     print("")
     input("Restart to see another index!")
elif index == 'What is Python?':
    input("Python is a programming language, that is simple and easy!")
    print("")
    input("Restart to see another index!")
elif index == 'What is PyCharm?':
    print("It's a programming software including Python, Java and HTML scripting!")
    print("")
    input("Restart to see another index!")
elif index == 'How to make salad':
    input("To make a salad you should follow these steps")
    print("")
    input("1. Grab vegetables")
    print("")
    input("2. Cut the vegetables")
    print("")
    input("3. Throw them into a dish")
    print("")
    input("4. Enjoy")
    print("")
    input("Restart to see another index!")
elif index == 'Index':
    input("An index is a collection of a group of assets")
    print("")
    input("This is a web index for everyone and made by Humans!")
    print("")
    input("Restart to see another index!")
elif index == 'About Index':
    input("Offline Web Index, 2015-2026")
    print("")
    print("This project is open-source, and free to use!")
    print("")
    print("You can get yours at: (No web page)")
    print("")
    print("And make your own offline web index!")
    print("")
    input("Restart to see another index!")
elif index == 'What is GitHub':
    input("GitHub is a free open space to upload your projects!")
    print("")
    input("Restart to see another index!")
elif index == 'Available index':
    print("Available index:")
    print("")
    input("Google")
    print("")
    input("Windows")
    print("")
    input("Python")
    print("")
    input("How to make salad (index recipe)")
    print("")
    input("About Index (Regular Index)")
    print("")
    input("Index (Index)")
    print("")
    input("Restart to see another index!")
elif index == 'Revision':
    print("Revision 'Term'")
    print("")
    input("Press enter to see the Term meaning")
    print("")
    input("The revision term is about a reviewed program, which should complete these Review points")
    print("")
    input("It should update every week")
    input("It should have a good code (Without lots of bugs)")
    input("And it should have atleast 3.1 points to be a Revision program")
    print("")
    input("Index terms are W.I.P!")
    print("")
    input("Restart to see another index!")
elif index == 'Test term':
    print("This is a test term!")
    print("")
    input("Restart to see another index!")
elif index == 'What is RAM?':
    input("It's a very important component! Used in almost all types of machines!")
    print("")
    input("Restart to see another index!")
elif index == 'Create an index':
    input("This feature is not available")
elif index == 'What is a protogen?':
    input("idk why did you ask?")
else:
   print("Unknown index!")
   print("")
   input("Please search an available index!") 
